services:
  api:
    build:
      context: .
      dockerfile: src/Web/ApiHost/Dockerfile
    container_name: vinva-gastronomy-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      Media__UploadsPath: /app/uploads
    ports:
      - "5134:8080"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: vinva-gastronomy-nginx
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./src/Web/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./uploads:/usr/share/nginx/uploads:ro
    restart: unless-stopped