// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthenticationLoginData, AuthenticationLoginResponses, AuthenticationLogoutData, AuthenticationLogoutResponses, AuthenticationMeData, AuthenticationMeResponses, AuthenticationRefreshTokenData, AuthenticationRefreshTokenResponses, ImageCreateImageData, ImageCreateImageResponses, ImageGetImagesByIdsData, ImageGetImagesByIdsResponses, IngredientCreateData, IngredientCreateResponses, IngredientGetByIdData, IngredientGetByIdResponses, IngredientRemoveData, IngredientRemoveResponses, IngredientUpdateData, IngredientUpdateResponses, RecipeCreateData, RecipeCreateResponses, RecipeRemoveData, RecipeRemoveResponses, RecipeSearchByIngredientsData, RecipeSearchByIngredientsResponses, RecipeSearchByQueryData, RecipeSearchByQueryResponses, RecipeUpdateData, RecipeUpdateResponses, RegistrationRegisterConfirmData, RegistrationRegisterConfirmResponses, RegistrationRegisterData, RegistrationRegisterResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const authenticationLogin = <ThrowOnError extends boolean = false>(options?: Options<AuthenticationLoginData, ThrowOnError>): RequestResult<AuthenticationLoginResponses, unknown, ThrowOnError> => (options?.client ?? client).post<AuthenticationLoginResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Authentication/Login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const authenticationRefreshToken = <ThrowOnError extends boolean = false>(options?: Options<AuthenticationRefreshTokenData, ThrowOnError>): RequestResult<AuthenticationRefreshTokenResponses, unknown, ThrowOnError> => (options?.client ?? client).post<AuthenticationRefreshTokenResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Authentication/RefreshToken',
    ...options
});

export const authenticationMe = <ThrowOnError extends boolean = false>(options?: Options<AuthenticationMeData, ThrowOnError>): RequestResult<AuthenticationMeResponses, unknown, ThrowOnError> => (options?.client ?? client).get<AuthenticationMeResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Authentication/Me',
    ...options
});

export const authenticationLogout = <ThrowOnError extends boolean = false>(options?: Options<AuthenticationLogoutData, ThrowOnError>): RequestResult<AuthenticationLogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<AuthenticationLogoutResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Authentication/Logout',
    ...options
});

export const imageGetImagesByIds = <ThrowOnError extends boolean = false>(options?: Options<ImageGetImagesByIdsData, ThrowOnError>): RequestResult<ImageGetImagesByIdsResponses, unknown, ThrowOnError> => (options?.client ?? client).post<ImageGetImagesByIdsResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Images/GetByIds',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const imageCreateImage = <ThrowOnError extends boolean = false>(options?: Options<ImageCreateImageData, ThrowOnError>): RequestResult<ImageCreateImageResponses, unknown, ThrowOnError> => (options?.client ?? client).post<ImageCreateImageResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Images/Create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const ingredientCreate = <ThrowOnError extends boolean = false>(options?: Options<IngredientCreateData, ThrowOnError>): RequestResult<IngredientCreateResponses, unknown, ThrowOnError> => (options?.client ?? client).post<IngredientCreateResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Ingredients/Create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const ingredientGetById = <ThrowOnError extends boolean = false>(options?: Options<IngredientGetByIdData, ThrowOnError>): RequestResult<IngredientGetByIdResponses, unknown, ThrowOnError> => (options?.client ?? client).get<IngredientGetByIdResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Ingredients/GetById',
    ...options
});

export const ingredientRemove = <ThrowOnError extends boolean = false>(options?: Options<IngredientRemoveData, ThrowOnError>): RequestResult<IngredientRemoveResponses, unknown, ThrowOnError> => (options?.client ?? client).delete<IngredientRemoveResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Ingredients/Remove',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const ingredientUpdate = <ThrowOnError extends boolean = false>(options?: Options<IngredientUpdateData, ThrowOnError>): RequestResult<IngredientUpdateResponses, unknown, ThrowOnError> => (options?.client ?? client).patch<IngredientUpdateResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Ingredients/Update',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const recipeCreate = <ThrowOnError extends boolean = false>(options?: Options<RecipeCreateData, ThrowOnError>): RequestResult<RecipeCreateResponses, unknown, ThrowOnError> => (options?.client ?? client).post<RecipeCreateResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Recipes/Create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const recipeSearchByIngredients = <ThrowOnError extends boolean = false>(options?: Options<RecipeSearchByIngredientsData, ThrowOnError>): RequestResult<RecipeSearchByIngredientsResponses, unknown, ThrowOnError> => (options?.client ?? client).post<RecipeSearchByIngredientsResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Recipes/SearchByIngredients',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const recipeSearchByQuery = <ThrowOnError extends boolean = false>(options?: Options<RecipeSearchByQueryData, ThrowOnError>): RequestResult<RecipeSearchByQueryResponses, unknown, ThrowOnError> => (options?.client ?? client).post<RecipeSearchByQueryResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Recipes/SearchByQuery',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const recipeRemove = <ThrowOnError extends boolean = false>(options?: Options<RecipeRemoveData, ThrowOnError>): RequestResult<RecipeRemoveResponses, unknown, ThrowOnError> => (options?.client ?? client).delete<RecipeRemoveResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Recipes/Remove',
    ...options
});

export const recipeUpdate = <ThrowOnError extends boolean = false>(options?: Options<RecipeUpdateData, ThrowOnError>): RequestResult<RecipeUpdateResponses, unknown, ThrowOnError> => (options?.client ?? client).patch<RecipeUpdateResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Recipes/Update',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const registrationRegister = <ThrowOnError extends boolean = false>(options?: Options<RegistrationRegisterData, ThrowOnError>): RequestResult<RegistrationRegisterResponses, unknown, ThrowOnError> => (options?.client ?? client).post<RegistrationRegisterResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Registration/Register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const registrationRegisterConfirm = <ThrowOnError extends boolean = false>(options?: Options<RegistrationRegisterConfirmData, ThrowOnError>): RequestResult<RegistrationRegisterConfirmResponses, unknown, ThrowOnError> => (options?.client ?? client).post<RegistrationRegisterConfirmResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Registration/RegisterConfirm',
    ...options
});
