// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthenticationLoginData, AuthenticationLoginResponses, AuthenticationLogoutData, AuthenticationLogoutResponses, AuthenticationMeData, AuthenticationMeResponses, AuthenticationRefreshTokenData, AuthenticationRefreshTokenResponses, CategoryCreateData, CategoryCreateResponses, CategoryRemoveData, CategoryRemoveResponses, ImageCreateImageData, ImageCreateImageResponses, ImageGetImagesByIdsData, ImageGetImagesByIdsResponses, IngredientCreateData, IngredientCreateResponses, IngredientGetByIdData, IngredientGetByIdResponses, IngredientRemoveData, IngredientRemoveResponses, IngredientUpdateData, IngredientUpdateResponses, RecipeAddCategoriesData, RecipeAddCategoriesResponses, RecipeAddIngredientsData, RecipeAddIngredientsResponses, RecipeAddStepsData, RecipeAddStepsResponses, RecipeCreateData, RecipeCreateResponses, RecipeRemoveCategoriesData, RecipeRemoveCategoriesResponses, RecipeRemoveData, RecipeRemoveIngredientsData, RecipeRemoveIngredientsResponses, RecipeRemoveResponses, RecipeRemoveStepsData, RecipeRemoveStepsResponses, RecipeReorderStepsData, RecipeReorderStepsResponses, RecipeSearchByCategoriesData, RecipeSearchByCategoriesResponses, RecipeSearchByIngredientsData, RecipeSearchByIngredientsResponses, RecipeSearchByQueryData, RecipeSearchByQueryResponses, RegistrationRegisterConfirmData, RegistrationRegisterConfirmResponses, RegistrationRegisterData, RegistrationRegisterResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const authenticationLogin = <ThrowOnError extends boolean = false>(options?: Options<AuthenticationLoginData, ThrowOnError>) => (options?.client ?? client).post<AuthenticationLoginResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Authentication/Login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const authenticationRefreshToken = <ThrowOnError extends boolean = false>(options?: Options<AuthenticationRefreshTokenData, ThrowOnError>) => (options?.client ?? client).post<AuthenticationRefreshTokenResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Authentication/RefreshToken',
    ...options
});

export const authenticationMe = <ThrowOnError extends boolean = false>(options?: Options<AuthenticationMeData, ThrowOnError>) => (options?.client ?? client).get<AuthenticationMeResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Authentication/Me',
    ...options
});

export const authenticationLogout = <ThrowOnError extends boolean = false>(options?: Options<AuthenticationLogoutData, ThrowOnError>) => (options?.client ?? client).post<AuthenticationLogoutResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Authentication/Logout',
    ...options
});

export const categoryCreate = <ThrowOnError extends boolean = false>(options?: Options<CategoryCreateData, ThrowOnError>) => (options?.client ?? client).post<CategoryCreateResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Categories/Create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const categoryRemove = <ThrowOnError extends boolean = false>(options?: Options<CategoryRemoveData, ThrowOnError>) => (options?.client ?? client).delete<CategoryRemoveResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Categories/Remove',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const imageGetImagesByIds = <ThrowOnError extends boolean = false>(options?: Options<ImageGetImagesByIdsData, ThrowOnError>) => (options?.client ?? client).post<ImageGetImagesByIdsResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Images/GetByIds',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const imageCreateImage = <ThrowOnError extends boolean = false>(options?: Options<ImageCreateImageData, ThrowOnError>) => (options?.client ?? client).post<ImageCreateImageResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Images/Create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const ingredientCreate = <ThrowOnError extends boolean = false>(options?: Options<IngredientCreateData, ThrowOnError>) => (options?.client ?? client).post<IngredientCreateResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Ingredients/Create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const ingredientGetById = <ThrowOnError extends boolean = false>(options?: Options<IngredientGetByIdData, ThrowOnError>) => (options?.client ?? client).get<IngredientGetByIdResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Ingredients/GetById',
    ...options
});

export const ingredientRemove = <ThrowOnError extends boolean = false>(options?: Options<IngredientRemoveData, ThrowOnError>) => (options?.client ?? client).delete<IngredientRemoveResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Ingredients/Remove',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const ingredientUpdate = <ThrowOnError extends boolean = false>(options?: Options<IngredientUpdateData, ThrowOnError>) => (options?.client ?? client).patch<IngredientUpdateResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Ingredients/Update',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const recipeAddIngredients = <ThrowOnError extends boolean = false>(options?: Options<RecipeAddIngredientsData, ThrowOnError>) => (options?.client ?? client).patch<RecipeAddIngredientsResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Recipes/AddIngredients',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const recipeAddCategories = <ThrowOnError extends boolean = false>(options?: Options<RecipeAddCategoriesData, ThrowOnError>) => (options?.client ?? client).patch<RecipeAddCategoriesResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Recipes/AddCategories',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const recipeAddSteps = <ThrowOnError extends boolean = false>(options?: Options<RecipeAddStepsData, ThrowOnError>) => (options?.client ?? client).patch<RecipeAddStepsResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Recipes/AddSteps',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const recipeCreate = <ThrowOnError extends boolean = false>(options?: Options<RecipeCreateData, ThrowOnError>) => (options?.client ?? client).post<RecipeCreateResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Recipes/Create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const recipeSearchByCategories = <ThrowOnError extends boolean = false>(options?: Options<RecipeSearchByCategoriesData, ThrowOnError>) => (options?.client ?? client).post<RecipeSearchByCategoriesResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Recipes/SearchByCategories',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const recipeSearchByIngredients = <ThrowOnError extends boolean = false>(options?: Options<RecipeSearchByIngredientsData, ThrowOnError>) => (options?.client ?? client).post<RecipeSearchByIngredientsResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Recipes/SearchByIngredients',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const recipeSearchByQuery = <ThrowOnError extends boolean = false>(options?: Options<RecipeSearchByQueryData, ThrowOnError>) => (options?.client ?? client).post<RecipeSearchByQueryResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Recipes/SearchByQuery',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const recipeRemove = <ThrowOnError extends boolean = false>(options?: Options<RecipeRemoveData, ThrowOnError>) => (options?.client ?? client).delete<RecipeRemoveResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Recipes/Remove',
    ...options
});

export const recipeRemoveIngredients = <ThrowOnError extends boolean = false>(options?: Options<RecipeRemoveIngredientsData, ThrowOnError>) => (options?.client ?? client).patch<RecipeRemoveIngredientsResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Recipes/RemoveIngredients',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const recipeRemoveCategories = <ThrowOnError extends boolean = false>(options?: Options<RecipeRemoveCategoriesData, ThrowOnError>) => (options?.client ?? client).patch<RecipeRemoveCategoriesResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Recipes/RemoveCategories',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const recipeRemoveSteps = <ThrowOnError extends boolean = false>(options?: Options<RecipeRemoveStepsData, ThrowOnError>) => (options?.client ?? client).patch<RecipeRemoveStepsResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Recipes/RemoveSteps',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const recipeReorderSteps = <ThrowOnError extends boolean = false>(options?: Options<RecipeReorderStepsData, ThrowOnError>) => (options?.client ?? client).patch<RecipeReorderStepsResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Recipes/ReorderSteps',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const registrationRegister = <ThrowOnError extends boolean = false>(options?: Options<RegistrationRegisterData, ThrowOnError>) => (options?.client ?? client).post<RegistrationRegisterResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Registration/Register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const registrationRegisterConfirm = <ThrowOnError extends boolean = false>(options?: Options<RegistrationRegisterConfirmData, ThrowOnError>) => (options?.client ?? client).post<RegistrationRegisterConfirmResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'accessToken',
            type: 'apiKey'
        }],
    url: '/api/Registration/RegisterConfirm',
    ...options
});
