// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Condition = {
    logic: Logic;
    field: string | null;
    operator: Operator;
    value: unknown;
};

export type CreateImageCommandResponse = {
    imageId: string;
};

export type CreateIngredientCommand = {
    name?: string | null;
    description?: string | null;
    comment?: string | null;
};

export type CreateIngredientResponse = {
    ingredientId?: string;
};

export type CreateRecipeCommand = {
    name?: string | null;
    description?: string | null;
    comment?: string | null;
    cookingTime?: string;
    baseRecipe?: string | null;
    storageComment?: string | null;
    usageComment?: string | null;
};

export type CreateRecipeResponce = {
    recipeId?: string;
    name?: string | null;
};

export enum DtoState {
    NONE = 'None',
    NEW = 'New',
    CHANGE = 'Change',
    REMOVE = 'Remove'
}

export type GetImagesByIdsQuery = {
    imageDtos: Array<ImageQueryDto> | null;
};

export type GetImagesByIdsQueryResponse = {
    items: Array<ImageResponceDto> | null;
};

export type GetIngredientByIdResponce = {
    ingredient?: IngredientDto;
};

export type GetRecipeByIngredientsRequest = {
    include?: Array<string> | null;
    exclude?: Array<string> | null;
    includeLogicAnd?: boolean;
};

export type GetRecipeByIngredientsResponce = {
    recipes?: Array<RecipeDto> | null;
};

export type GetRecipesByFilterQuery = {
    query: SearchQuery;
};

export type GetRecipesByFilterQueryResponse = {
    recipes?: Array<RecipeDto> | null;
};

export type ImageQueryDto = {
    imageId: string;
    width: number;
    height: number;
    quality: number;
    format: string | null;
};

export type ImageResponceDto = {
    imageId?: string;
    url: string | null;
};

export type IngredientDto = {
    id: string;
    name: string | null;
    description?: string | null;
    photoId?: string | null;
    recipeId?: string | null;
};

export type IngredientQuantityDto = {
    measure: string | null;
    quantity: number;
};

export enum Logic {
    OR = 'Or',
    AND = 'And'
}

export type LoginRequest = {
    login: string | null;
    password: string | null;
};

export enum Operator {
    LESS = 'Less',
    LESS_OR_EQUAL = 'LessOrEqual',
    LARGER = 'Larger',
    LARGER_OR_EQUAL = 'LargerOrEqual',
    EQUALS = 'Equals',
    NOT_EQUALS = 'NotEquals',
    START_WITH = 'StartWith',
    END_WITH = 'EndWith',
    CONTAINS = 'Contains'
}

export type RecipeDto = {
    id: string;
    name: string | null;
    description?: string | null;
    comment?: string | null;
    baseRecipe?: string | null;
    titleImageId?: string | null;
    videoId?: string | null;
    cookingTime?: string | null;
    cookingComment?: string | null;
    ingredientComment?: string | null;
    storageComment?: string | null;
    usageComment?: string | null;
    otherImageIds?: Array<string> | null;
    ingredients?: Array<RecipeIngredientDto> | null;
    properties?: Array<RecipePropertyDto> | null;
    steps?: Array<RecipeStepDto> | null;
};

export type RecipeIngredientDto = {
    ingredientId: string;
    ingredientName: string | null;
    comment?: string | null;
    isRequired?: boolean;
    quantities: Array<IngredientQuantityDto> | null;
    state?: DtoState;
};

export type RecipePropertyDto = {
    name: string | null;
    values: Array<string> | null;
};

export type RecipeStepDto = {
    id?: string;
    description: string | null;
    comment?: string | null;
    seqNumber: number;
    photoId?: string | null;
    state?: DtoState;
};

export type RegisterCommand = {
    password?: string | null;
    login?: string | null;
    email?: string | null;
};

export type RegisterCommandResponce = {
    details?: string | null;
};

export type RemoveIngredientCommand = {
    ingredientId?: string;
};

export type SearchQuery = {
    take?: number;
    skip?: number;
    sort?: Sorting;
    conditions?: Array<Condition> | null;
};

export enum SortDirection {
    ASCENDING = 'Ascending',
    DESCENDING = 'Descending'
}

export type Sorting = {
    property: string | null;
    direction?: SortDirection;
};

export type UpdateCommand = {
    id: string;
    name?: string | null;
    description?: string | null;
    comment?: string | null;
    cookingTime?: string | null;
    baseRecipe?: string | null;
    storageComment?: string | null;
    usageComment?: string | null;
    ingredientComment?: string | null;
    cookingComment?: string | null;
    steps?: Array<RecipeStepDto> | null;
    ingredients?: Array<RecipeIngredientDto> | null;
    properties?: Array<RecipePropertyDto> | null;
};

export type UpdateIngredientCommand = {
    id?: string;
    name?: string | null;
    description?: string | null;
    comment?: string | null;
    usageComment?: string | null;
    photoId?: string | null;
    recipeId?: string | null;
};

export type UserInfoDto = {
    id: string;
    login: string | null;
    email: string | null;
    state: UserState;
    roles: Array<UserRole> | null;
};

export enum UserRole {
    CLIENT = 'Client',
    MANAGER = 'Manager',
    ADMIN = 'Admin'
}

export enum UserState {
    ACTIVE = 'Active',
    BLOCKED = 'Blocked',
    UNACTIVE = 'Unactive'
}

export type AuthenticationLoginData = {
    body?: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/Authentication/Login';
};

export type AuthenticationLoginResponses = {
    /**
     * OK
     */
    200: UserInfoDto;
};

export type AuthenticationLoginResponse = AuthenticationLoginResponses[keyof AuthenticationLoginResponses];

export type AuthenticationRefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Authentication/RefreshToken';
};

export type AuthenticationRefreshTokenResponses = {
    /**
     * OK
     */
    200: UserInfoDto;
};

export type AuthenticationRefreshTokenResponse = AuthenticationRefreshTokenResponses[keyof AuthenticationRefreshTokenResponses];

export type AuthenticationMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Authentication/Me';
};

export type AuthenticationMeResponses = {
    /**
     * OK
     */
    200: UserInfoDto;
};

export type AuthenticationMeResponse = AuthenticationMeResponses[keyof AuthenticationMeResponses];

export type AuthenticationLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Authentication/Logout';
};

export type AuthenticationLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ImageGetImagesByIdsData = {
    body?: GetImagesByIdsQuery;
    path?: never;
    query?: never;
    url: '/api/Images/GetByIds';
};

export type ImageGetImagesByIdsResponses = {
    /**
     * OK
     */
    200: GetImagesByIdsQueryResponse;
};

export type ImageGetImagesByIdsResponse = ImageGetImagesByIdsResponses[keyof ImageGetImagesByIdsResponses];

export type ImageCreateImageData = {
    body?: {
        File: Blob | File;
        Group?: string;
    };
    path?: never;
    query?: never;
    url: '/api/Images/Create';
};

export type ImageCreateImageResponses = {
    /**
     * OK
     */
    200: CreateImageCommandResponse;
};

export type ImageCreateImageResponse = ImageCreateImageResponses[keyof ImageCreateImageResponses];

export type IngredientCreateData = {
    body?: CreateIngredientCommand;
    path?: never;
    query?: never;
    url: '/api/Ingredients/Create';
};

export type IngredientCreateResponses = {
    /**
     * OK
     */
    200: CreateIngredientResponse;
};

export type IngredientCreateResponse = IngredientCreateResponses[keyof IngredientCreateResponses];

export type IngredientGetByIdData = {
    body?: never;
    path?: never;
    query?: {
        ingredientId?: string;
    };
    url: '/api/Ingredients/GetById';
};

export type IngredientGetByIdResponses = {
    /**
     * OK
     */
    200: GetIngredientByIdResponce;
};

export type IngredientGetByIdResponse = IngredientGetByIdResponses[keyof IngredientGetByIdResponses];

export type IngredientRemoveData = {
    body?: RemoveIngredientCommand;
    path?: never;
    query?: never;
    url: '/api/Ingredients/Remove';
};

export type IngredientRemoveResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type IngredientUpdateData = {
    body?: UpdateIngredientCommand;
    path?: never;
    query?: never;
    url: '/api/Ingredients/Update';
};

export type IngredientUpdateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RecipeCreateData = {
    body?: CreateRecipeCommand;
    path?: never;
    query?: never;
    url: '/api/Recipes/Create';
};

export type RecipeCreateResponses = {
    /**
     * OK
     */
    200: CreateRecipeResponce;
};

export type RecipeCreateResponse = RecipeCreateResponses[keyof RecipeCreateResponses];

export type RecipeSearchByIngredientsData = {
    body?: GetRecipeByIngredientsRequest;
    path?: never;
    query?: never;
    url: '/api/Recipes/SearchByIngredients';
};

export type RecipeSearchByIngredientsResponses = {
    /**
     * OK
     */
    200: GetRecipeByIngredientsResponce;
};

export type RecipeSearchByIngredientsResponse = RecipeSearchByIngredientsResponses[keyof RecipeSearchByIngredientsResponses];

export type RecipeSearchByQueryData = {
    body?: GetRecipesByFilterQuery;
    path?: never;
    query?: never;
    url: '/api/Recipes/SearchByQuery';
};

export type RecipeSearchByQueryResponses = {
    /**
     * OK
     */
    200: GetRecipesByFilterQueryResponse;
};

export type RecipeSearchByQueryResponse = RecipeSearchByQueryResponses[keyof RecipeSearchByQueryResponses];

export type RecipeRemoveData = {
    body?: never;
    path?: never;
    query?: {
        recipeId?: string;
    };
    url: '/api/Recipes/Remove';
};

export type RecipeRemoveResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RecipeUpdateData = {
    body?: UpdateCommand;
    path?: never;
    query?: never;
    url: '/api/Recipes/Update';
};

export type RecipeUpdateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RegistrationRegisterData = {
    body?: RegisterCommand;
    path?: never;
    query?: never;
    url: '/api/Registration/Register';
};

export type RegistrationRegisterResponses = {
    /**
     * OK
     */
    200: RegisterCommandResponce;
};

export type RegistrationRegisterResponse = RegistrationRegisterResponses[keyof RegistrationRegisterResponses];

export type RegistrationRegisterConfirmData = {
    body?: never;
    path?: never;
    query?: {
        tokenId?: string;
    };
    url: '/api/Registration/RegisterConfirm';
};

export type RegistrationRegisterConfirmResponses = {
    /**
     * OK
     */
    200: unknown;
};
