// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AddIngredientCommand = {
    recipeId?: string;
    ingredients?: Array<RecipeIngredientDto> | null;
};

export type AddRecipeCategoriesCommand = {
    recipeId?: string;
    categoryIds?: Array<string> | null;
};

export type AddStepsCommand = {
    recipeId: string;
    steps?: Array<RecipeStepDto> | null;
};

export type CategoryDto = {
    id?: string;
    name?: string | null;
    description?: string | null;
    comment?: string | null;
    type?: 'Recipe' | 'Ingredient';
};

export type ChangeSeqNumberDto = {
    seqNumber1?: number;
    seqNumber2?: number;
};

export type Condition = {
    logic: 'Or' | 'And';
    field: string | null;
    operator: 'Less' | 'LessOrEqual' | 'Larger' | 'LargerOrEqual' | 'Equals' | 'NotEquals' | 'StartWith' | 'EndWith' | 'Contains';
    value: unknown;
};

export type CreateCategoryCommand = {
    name?: string | null;
    description?: string | null;
    comment?: string | null;
    type?: 'Recipe' | 'Ingredient';
};

export type CreateCategoryResponse = {
    categoryId?: string;
};

export type CreateImageCommandResponse = {
    imageId: string;
};

export type CreateIngredientCommand = {
    name?: string | null;
    description?: string | null;
    usageComment?: string | null;
};

export type CreateIngredientResponse = {
    ingredientId?: string;
};

export type CreateRecipeCommand = {
    name?: string | null;
    description?: string | null;
    comment?: string | null;
    cookingTime?: string;
    baseRecipe?: string | null;
    storageComment?: string | null;
    usageComment?: string | null;
};

export type CreateRecipeResponce = {
    recipeId?: string;
    name?: string | null;
};

export type GetImagesByIdsQuery = {
    imageDtos: Array<ImageQueryDto> | null;
};

export type GetImagesByIdsQueryResponse = {
    items: Array<ImageResponceDto> | null;
};

export type GetIngredientByIdResponce = {
    ingredient?: IngredientDto;
};

export type GetRecipeByCategoryRequest = {
    include?: Array<string> | null;
    exclude?: Array<string> | null;
    includeLogicAnd?: boolean;
};

export type GetRecipeByCategoryResponce = {
    recipes?: Array<RecipeDto> | null;
};

export type GetRecipeByIngredientsRequest = {
    include?: Array<string> | null;
    exclude?: Array<string> | null;
    includeLogicAnd?: boolean;
};

export type GetRecipeByIngredientsResponce = {
    recipes?: Array<RecipeDto> | null;
};

export type GetRecipesByFilterQuery = {
    query: SearchQuery;
};

export type GetRecipesByFilterQueryResponse = {
    recipes?: Array<RecipeDto> | null;
};

export type ImageQueryDto = {
    imageId: string;
    width: number;
    height: number;
    quality: number;
    format: string | null;
};

export type ImageResponceDto = {
    imageId?: string;
    url: string | null;
};

export type IngredientCategoryDto = {
    id: string;
    name: string | null;
    description?: string | null;
};

export type IngredientDto = {
    id: string;
    name: string | null;
    description?: string | null;
    usageComment?: string | null;
    photoId?: string | null;
    recipeId?: string | null;
    categories?: Array<IngredientCategoryDto> | null;
};

export type IngredientQuantityDto = {
    measure: string | null;
    quantity: number;
};

export type LoginRequest = {
    login: string | null;
    password: string | null;
};

export type RecipeCategoryDto = {
    id: string;
    name: string | null;
    description?: string | null;
};

export type RecipeDto = {
    id: string;
    name: string | null;
    description?: string | null;
    baseRecipe?: string | null;
    photoId?: string | null;
    videoId?: string | null;
    cookingTime?: string | null;
    cookingComment?: string | null;
    ingredientComment?: string | null;
    storageComment?: string | null;
    usageComment?: string | null;
    ingredients?: Array<RecipeIngredientDto> | null;
    categories?: Array<RecipeCategoryDto> | null;
    steps?: Array<RecipeStepDto> | null;
};

export type RecipeIngredientDto = {
    ingredientId: string;
    ingredientName: string | null;
    isRequired?: boolean;
    quantities: Array<IngredientQuantityDto> | null;
};

export type RecipeStepDto = {
    description: string | null;
    comment?: string | null;
    seqNumber: number;
    photoId?: string | null;
};

export type RegisterCommand = {
    password?: string | null;
    login?: string | null;
    email?: string | null;
};

export type RegisterCommandResponce = {
    details?: string | null;
};

export type RemoveCategoryCommand = {
    categoryId?: string;
};

export type RemoveIngredientCommand = {
    ingredientId?: string;
};

export type RemoveIngredientsCommand = {
    recipeId?: string;
    ingredientIds?: Array<string> | null;
};

export type RemoveRecipeCategoryCommand = {
    recipeId?: string;
    categoryIds?: Array<string> | null;
};

export type RemoveStepsCommand = {
    recipeId: string;
    seqNumbers: Array<number> | null;
};

export type ReorderStepsCommand = {
    recipeId?: string;
    items?: Array<ChangeSeqNumberDto> | null;
};

export type SearchCategoriesQuery = {
    query: SearchQuery;
};

export type SearchCategoriesQueryResponse = {
    items: Array<CategoryDto> | null;
};

export type SearchQuery = {
    take?: number;
    skip?: number;
    sort?: Sorting;
    conditions?: Array<Condition> | null;
};

export type Sorting = {
    property: string | null;
    direction?: 'Ascending' | 'Descending';
};

export type UpdateIngredientCommand = {
    id?: string;
    name?: string | null;
    description?: string | null;
    comment?: string | null;
    usageComment?: string | null;
    photoId?: string | null;
    recipeId?: string | null;
};

export type UserInfoDto = {
    id: string;
    login: string | null;
    email: string | null;
    state: 'Active' | 'Blocked' | 'Unactive';
    roles: Array<'Client' | 'Manager' | 'Admin'> | null;
};

export type AuthenticationLoginData = {
    body?: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/Authentication/Login';
};

export type AuthenticationLoginResponses = {
    /**
     * OK
     */
    200: UserInfoDto;
};

export type AuthenticationLoginResponse = AuthenticationLoginResponses[keyof AuthenticationLoginResponses];

export type AuthenticationRefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Authentication/RefreshToken';
};

export type AuthenticationRefreshTokenResponses = {
    /**
     * OK
     */
    200: UserInfoDto;
};

export type AuthenticationRefreshTokenResponse = AuthenticationRefreshTokenResponses[keyof AuthenticationRefreshTokenResponses];

export type AuthenticationMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Authentication/Me';
};

export type AuthenticationMeResponses = {
    /**
     * OK
     */
    200: UserInfoDto;
};

export type AuthenticationMeResponse = AuthenticationMeResponses[keyof AuthenticationMeResponses];

export type AuthenticationLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Authentication/Logout';
};

export type AuthenticationLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CategoryCreateData = {
    body?: CreateCategoryCommand;
    path?: never;
    query?: never;
    url: '/api/Categories/Create';
};

export type CategoryCreateResponses = {
    /**
     * OK
     */
    200: CreateCategoryResponse;
};

export type CategoryCreateResponse = CategoryCreateResponses[keyof CategoryCreateResponses];

export type CategorySearchData = {
    body?: SearchCategoriesQuery;
    path?: never;
    query?: never;
    url: '/api/Categories/Search';
};

export type CategorySearchResponses = {
    /**
     * OK
     */
    200: SearchCategoriesQueryResponse;
};

export type CategorySearchResponse = CategorySearchResponses[keyof CategorySearchResponses];

export type CategoryRemoveData = {
    body?: RemoveCategoryCommand;
    path?: never;
    query?: never;
    url: '/api/Categories/Remove';
};

export type CategoryRemoveResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ImageGetImagesByIdsData = {
    body?: GetImagesByIdsQuery;
    path?: never;
    query?: never;
    url: '/api/Images/GetByIds';
};

export type ImageGetImagesByIdsResponses = {
    /**
     * OK
     */
    200: GetImagesByIdsQueryResponse;
};

export type ImageGetImagesByIdsResponse = ImageGetImagesByIdsResponses[keyof ImageGetImagesByIdsResponses];

export type ImageCreateImageData = {
    body?: {
        File: Blob | File;
        Group?: string;
    };
    path?: never;
    query?: never;
    url: '/api/Images/Create';
};

export type ImageCreateImageResponses = {
    /**
     * OK
     */
    200: CreateImageCommandResponse;
};

export type ImageCreateImageResponse = ImageCreateImageResponses[keyof ImageCreateImageResponses];

export type IngredientCreateData = {
    body?: CreateIngredientCommand;
    path?: never;
    query?: never;
    url: '/api/Ingredients/Create';
};

export type IngredientCreateResponses = {
    /**
     * OK
     */
    200: CreateIngredientResponse;
};

export type IngredientCreateResponse = IngredientCreateResponses[keyof IngredientCreateResponses];

export type IngredientGetByIdData = {
    body?: never;
    path?: never;
    query?: {
        ingredientId?: string;
    };
    url: '/api/Ingredients/GetById';
};

export type IngredientGetByIdResponses = {
    /**
     * OK
     */
    200: GetIngredientByIdResponce;
};

export type IngredientGetByIdResponse = IngredientGetByIdResponses[keyof IngredientGetByIdResponses];

export type IngredientRemoveData = {
    body?: RemoveIngredientCommand;
    path?: never;
    query?: never;
    url: '/api/Ingredients/Remove';
};

export type IngredientRemoveResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type IngredientUpdateData = {
    body?: UpdateIngredientCommand;
    path?: never;
    query?: never;
    url: '/api/Ingredients/Update';
};

export type IngredientUpdateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RecipeAddIngredientsData = {
    body?: AddIngredientCommand;
    path?: never;
    query?: never;
    url: '/api/Recipes/AddIngredients';
};

export type RecipeAddIngredientsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RecipeAddCategoriesData = {
    body?: AddRecipeCategoriesCommand;
    path?: never;
    query?: never;
    url: '/api/Recipes/AddCategories';
};

export type RecipeAddCategoriesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RecipeAddStepsData = {
    body?: AddStepsCommand;
    path?: never;
    query?: never;
    url: '/api/Recipes/AddSteps';
};

export type RecipeAddStepsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RecipeCreateData = {
    body?: CreateRecipeCommand;
    path?: never;
    query?: never;
    url: '/api/Recipes/Create';
};

export type RecipeCreateResponses = {
    /**
     * OK
     */
    200: CreateRecipeResponce;
};

export type RecipeCreateResponse = RecipeCreateResponses[keyof RecipeCreateResponses];

export type RecipeSearchByCategoriesData = {
    body?: GetRecipeByCategoryRequest;
    path?: never;
    query?: never;
    url: '/api/Recipes/SearchByCategories';
};

export type RecipeSearchByCategoriesResponses = {
    /**
     * OK
     */
    200: GetRecipeByCategoryResponce;
};

export type RecipeSearchByCategoriesResponse = RecipeSearchByCategoriesResponses[keyof RecipeSearchByCategoriesResponses];

export type RecipeSearchByIngredientsData = {
    body?: GetRecipeByIngredientsRequest;
    path?: never;
    query?: never;
    url: '/api/Recipes/SearchByIngredients';
};

export type RecipeSearchByIngredientsResponses = {
    /**
     * OK
     */
    200: GetRecipeByIngredientsResponce;
};

export type RecipeSearchByIngredientsResponse = RecipeSearchByIngredientsResponses[keyof RecipeSearchByIngredientsResponses];

export type RecipeSearchByQueryData = {
    body?: GetRecipesByFilterQuery;
    path?: never;
    query?: never;
    url: '/api/Recipes/SearchByQuery';
};

export type RecipeSearchByQueryResponses = {
    /**
     * OK
     */
    200: GetRecipesByFilterQueryResponse;
};

export type RecipeSearchByQueryResponse = RecipeSearchByQueryResponses[keyof RecipeSearchByQueryResponses];

export type RecipeRemoveData = {
    body?: never;
    path?: never;
    query?: {
        recipeId?: string;
    };
    url: '/api/Recipes/Remove';
};

export type RecipeRemoveResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RecipeRemoveIngredientsData = {
    body?: RemoveIngredientsCommand;
    path?: never;
    query?: never;
    url: '/api/Recipes/RemoveIngredients';
};

export type RecipeRemoveIngredientsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RecipeRemoveCategoriesData = {
    body?: RemoveRecipeCategoryCommand;
    path?: never;
    query?: never;
    url: '/api/Recipes/RemoveCategories';
};

export type RecipeRemoveCategoriesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RecipeRemoveStepsData = {
    body?: RemoveStepsCommand;
    path?: never;
    query?: never;
    url: '/api/Recipes/RemoveSteps';
};

export type RecipeRemoveStepsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RecipeReorderStepsData = {
    body?: ReorderStepsCommand;
    path?: never;
    query?: never;
    url: '/api/Recipes/ReorderSteps';
};

export type RecipeReorderStepsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RegistrationRegisterData = {
    body?: RegisterCommand;
    path?: never;
    query?: never;
    url: '/api/Registration/Register';
};

export type RegistrationRegisterResponses = {
    /**
     * OK
     */
    200: RegisterCommandResponce;
};

export type RegistrationRegisterResponse = RegistrationRegisterResponses[keyof RegistrationRegisterResponses];

export type RegistrationRegisterConfirmData = {
    body?: never;
    path?: never;
    query?: {
        tokenId?: string;
    };
    url: '/api/Registration/RegisterConfirm';
};

export type RegistrationRegisterConfirmResponses = {
    /**
     * OK
     */
    200: unknown;
};
