<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
	<LangVersion>11</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Vinva.Gastronomy.Common\Vinva.Gastronomy.Common.csproj" />
  </ItemGroup>

</Project>
