<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="RemoveCategory\**" />
    <Compile Remove="UpdateIngredient\**" />
    <Compile Remove="UpdateRecipe\**" />
    <EmbeddedResource Remove="RemoveCategory\**" />
    <EmbeddedResource Remove="UpdateIngredient\**" />
    <EmbeddedResource Remove="UpdateRecipe\**" />
    <None Remove="RemoveCategory\**" />
    <None Remove="UpdateIngredient\**" />
    <None Remove="UpdateRecipe\**" />
  </ItemGroup>
  

	<ItemGroup>
		<PackageReference Include="MediatR" Version="13.1.0" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Vinva.Gastronomy.Common.Infrastructure\Vinva.Gastronomy.Common.Infrastructure.csproj" />
    <ProjectReference Include="..\Vinva.Gastronomy.Recipes.Domain\Vinva.Gastronomy.Recipes.Domain.csproj" />
    <ProjectReference Include="..\Vinva.Gastronomy.Recipes.Persistence\Vinva.Gastronomy.Recipes.Persistence.csproj" />
  </ItemGroup>

</Project>
